#!/bin/sh

rc_start() {
	/usr/local/bin/php -f /usr/local/pkg/wireguard/wg_service.inc wg_service_start
	/usr/local/bin/php_wg -f /usr/local/pkg/wireguard/wg_service.inc wg_service_watchdog
}

rc_stop() {
	/usr/local/bin/php -f /usr/local/pkg/wireguard/wg_service.inc wg_service_stop
}

case $1 in
	start)
		rc_start
		;;
	stop)
		rc_stop
		;;
	restart)
		rc_stop
		rc_start
		;;
esac

